#ifndef _CHGAME_SETTING
#define _CHGAME_SETTING


#define ELECTRON_EVENT_ID_BEGIN                 100
#define ELECTRON_INTERFACE_ID_BEGIN             100
#define ELECTRON_OBJECT_ID_BEGIN                OID_ATOM_END + 100
#define ELECTRON_SINGLETON_OBJECT_ID_BEGIN      OID_ATOM_SINGLETON_END + 100


#define GULON_INTERFACE_ID_BEGIN                200
#define GULON_SINGLETON_OBJECT_ID_BEGIN         OID_ATOM_SINGLETON_END + 200


#define NEUTRON_EVENT_ID_BEGIN                  300
#define NEUTRON_INTERFACE_ID_BEGIN              300
#define NEUTRON_OBJECT_ID_BEGIN                 OID_ATOM_END + 300
#define NEUTRON_SINGLETON_OBJECT_ID_BEGIN       OID_ATOM_SINGLETON_END + 300


#define MESON_EVENT_ID_BEGIN                    400
#define MESON_INTERFACE_ID_BEGIN                400
#define MESON_MESSAGE_ID_BEGIN                  400
#define MESON_OBJECT_ID_BEGIN                   OID_ATOM_END + 400
#define MESON_SINGLETON_OBJECT_ID_BEGIN         OID_ATOM_SINGLETON_END + 400


#define PHOTON_EVENT_ID_BEGIN                   500
#define PHOTON_INTERFACE_ID_BEGIN               500
#define PHOTON_MESSAGE_ID_BEGIN                 500
#define PHOTON_OBJECT_ID_BEGIN                  OID_ATOM_END + 500
#define PHOTON_SINGLETON_OBJECT_ID_BEGIN        OID_ATOM_SINGLETON_END + 500


#define NOVA_EVENT_ID_BEGIN                     600
#define NOVA_INTERFACE_ID_BEGIN                 600
#define NOVA_MESSAGE_ID_BEGIN                   600
#define NOVA_PROCEDURE_RESULT_ID_BEGIN          600
#define NOVA_OBJECT_ID_BEGIN                    OID_ATOM_END + 600
#define NOVA_SINGLETON_OBJECT_ID_BEGIN          OID_ATOM_SINGLETON_END + 600


#define MASS_EVENT_ID_BEGIN                     700
#define MASS_INTERFACE_ID_BEGIN                 700
#define NASS_MESSAGE_ID_BEGIN                   700
#define MASS_OBJECT_ID_BEGIN                    OID_ATOM_END + 700
#define MASS_SINGLETON_OBJECT_ID_BEGIN          OID_ATOM_SINGLETON_END + 700


#define CHAT_EVENT_ID_BEGIN                     800
#define CHAT_INTERFACE_ID_BEGIN                 800
#define CHAT_MESSAGE_ID_BEGIN                   800
#define CHAT_OBJECT_ID_BEGIN                    OID_ATOM_END + 800
#define CHAT_SINGLETON_OBJECT_ID_BEGIN          OID_ATOM_SINGLETON_END + 800


#define VERSION_EVENT_ID_BEGIN                  900
#define VERSION_INTERFACE_ID_BEGIN              900
#define VERSION_MESSAGE_ID_BEGIN                900
#define VERSION_PROCEDURE_RESULT_ID_BEGIN       900
#define VERSION_OBJECT_ID_BEGIN                 OID_ATOM_END + 900
#define VERSION_SINGLETON_OBJECT_ID_BEGIN       OID_ATOM_SINGLETON_END + 900


#endif
